/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import classes.Employee;
import com.opencsv.exceptions.CsvValidationException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ajbab
 */
public class FrmMainMenu extends javax.swing.JDialog {

    /**
     * Creates new form FrmMainMenu
     */
    public FrmMainMenu() {
        this.setModalityType(ModalityType.APPLICATION_MODAL);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAddEmployee = new javax.swing.JButton();
        BtnUpdateEmployee = new javax.swing.JButton();
        BtnDeleteEmployee = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployeeDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnAttendance = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                LoadStudents(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(100, 195, 242));

        BtnAddEmployee.setBackground(new java.awt.Color(203, 238, 228));
        BtnAddEmployee.setText("Add Employee");
        BtnAddEmployee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAddEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddStudent(evt);
            }
        });
        BtnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddEmployeeActionPerformed(evt);
            }
        });

        BtnUpdateEmployee.setBackground(new java.awt.Color(246, 243, 188));
        BtnUpdateEmployee.setText("Update Employee");
        BtnUpdateEmployee.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnUpdateEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateStudent(evt);
            }
        });
        BtnUpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateEmployeeActionPerformed(evt);
            }
        });

        BtnDeleteEmployee.setBackground(new java.awt.Color(243, 155, 155));
        BtnDeleteEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnDeleteEmployee.setText("Delete Employee");
        BtnDeleteEmployee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnDeleteEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteEmployee(evt);
            }
        });
        BtnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteEmployeeActionPerformed(evt);
            }
        });

        tblEmployeeDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tblEmployeeDetails);
        if (tblEmployeeDetails.getColumnModel().getColumnCount() > 0) {
            tblEmployeeDetails.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            tblEmployeeDetails.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tblEmployeeDetails.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tblEmployeeDetails.getColumnModel().getColumn(3).setHeaderValue("Title 4");
            tblEmployeeDetails.getColumnModel().getColumn(4).setHeaderValue("Title 5");
        }

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("YouYuan", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MotorPH Employee App");

        BtnAttendance.setBackground(new java.awt.Color(0, 102, 102));
        BtnAttendance.setFont(new java.awt.Font("STZhongsong", 1, 14)); // NOI18N
        BtnAttendance.setForeground(new java.awt.Color(255, 255, 255));
        BtnAttendance.setText("Attendance");
        BtnAttendance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAttendanceMouseClicked(evt);
            }
        });
        BtnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Timein(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Payroll");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(BtnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(BtnUpdateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnDeleteEmployee)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(BtnAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAddEmployee)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnUpdateEmployee)
                        .addComponent(BtnDeleteEmployee)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStudent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStudent
        FrmNewEmployee _addemployee = new FrmNewEmployee();
        _addemployee.pack();
        _addemployee.setVisible(true);
        String csvFilename = "Employees.csv";
        Employee _employee = new Employee();
        try {
            tblEmployeeDetails.setModel(_employee.FetchEmployees(csvFilename));
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddStudent

    private void UpdateStudent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateStudent
        Employee _employee = new Employee();
        _employee.SetEmployeeNo(tblEmployeeDetails.getModel().getValueAt(tblEmployeeDetails.getSelectedRow(), 0).toString());
        _employee.SetEmployeeName(tblEmployeeDetails.getModel().getValueAt(tblEmployeeDetails.getSelectedRow(), 1).toString());
        _employee.SetEmployeeAddress(tblEmployeeDetails.getModel().getValueAt(tblEmployeeDetails.getSelectedRow(), 2).toString());
        FrmEditEmployee _editStudent = new FrmEditEmployee(_employee);
        _editStudent.pack();
        _editStudent.setVisible(true);
      
        String csvFilename = ".csv";
        try {
            tblEmployeeDetails.setModel(_employee.FetchEmployees(csvFilename));
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_UpdateStudent

    private void LoadStudents(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_LoadStudents
        String csvFilename = "Employees.csv";
        Employee _employee = new Employee();
        try {
            tblEmployeeDetails.setModel(_employee.FetchEmployees(csvFilename));
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LoadStudents

    private void DeleteEmployee(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteEmployee
        Employee _employee = new Employee();
        _employee.SetEmployeeNo(tblEmployeeDetails.getModel().getValueAt(tblEmployeeDetails.getSelectedRow(), 0).toString());
        _employee.SetEmployeeName(tblEmployeeDetails.getModel().getValueAt(tblEmployeeDetails.getSelectedRow(), 1).toString());
        _employee.SetEmployeeAddress(tblEmployeeDetails.getModel().getValueAt(tblEmployeeDetails.getSelectedRow(), 2).toString());
        FrmDeleteEmployee _delete = new FrmDeleteEmployee(_employee);
        _delete.setVisible(true);
        String csvFilename = "Employees.csv";
        try {
            tblEmployeeDetails.setModel(_employee.FetchEmployees(csvFilename));
        } catch (IOException | CsvValidationException ex){
            Logger.getLogger(FrmMainMenu.class.getName()).log(Level.INFO, "An unexpected error occured.", ex);
        }
    }//GEN-LAST:event_DeleteEmployee

    private void BtnUpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdateEmployeeActionPerformed

    private void BtnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAddEmployeeActionPerformed

    private void BtnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeleteEmployeeActionPerformed

    private void BtnAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAttendanceMouseClicked
      
    }//GEN-LAST:event_BtnAttendanceMouseClicked

    private void Timein(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Timein
        FrmAttendance attendance = new FrmAttendance();
        attendance.show();
        
        dispose();
    }//GEN-LAST:event_Timein
    
    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddEmployee;
    private javax.swing.JButton BtnAttendance;
    private javax.swing.JButton BtnDeleteEmployee;
    private javax.swing.JButton BtnUpdateEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployeeDetails;
    // End of variables declaration//GEN-END:variables

}
